---
- name: Create directory
  file: path=/media/images/elasticsearch-copy state=directory mode=0777

- name: Copy elastic search data
  copy:
   src: /var/lib/elasticsearch
   dest: /media/images/elasticsearch-backup



